name: tfsec

on:
  push:
    branches:
      - production
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - production
    paths-ignore:
      - README.md

permissions:
  contents: read
  packages: write

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        run: terraform init

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: . # Change working directory
          level: info # Get more output from reviewdog
          reporter: github-pr-review # Change reviewdog reporter
          filter_mode: nofilter # Check all files, not just the diff
          fail_on_error: false # Fail action if errors are found
          flags: -tee # Add debug flag to reviewdog
          tfsec_flags: "" # Optional
        if: |
          (github.event_name == 'pull_request')

      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "${{ github.repository }}: ${{ github.workflow }}"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
