name: tfsec

on:
  push:
    branches:
      - production
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - production
    paths-ignore:
      - README.md

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        run: terraform init

      - name: Run tfsec
        run: |
          pip3 install lastversion
          lastversion tfsec/tfsec --assets -d
          chmod +x tfsec-linux-amd64
          ./tfsec-linux-amd64 . --soft-fail

      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: . # Change working directory
          level: info # Get more output from reviewdog
          reporter: github-pr-review # Change reviewdog reporter
          filter_mode: nofilter # Check all files, not just the diff
          fail_on_error: false # Fail action if errors are found
          flags: -tee # Add debug flag to reviewdog
          tfsec_flags: "" # Optional
        if: |
          (github.event_name == 'pull_request')
